import Footer from "@/layout/Footer";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <div>{children}<Footer /></div>

  )
}
