import Layout from "@/layout/Layout";
import localFont from "next/font/local";
import Navbar from "@/layout/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function FaqLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <Layout>
          {children}
        </Layout>
      </body>
    </html>
  );
}
